include:
  - path: docker/nexus/compose.yml
    env_file: .env
  - path: docker/redis/compose.yml
    env_file: .env
  - path: docker/backend/compose.yml
    env_file: .env
  - path: docker/frontend-web/compose.yml
    env_file: .env

networks:
  clinic_net:
    driver: bridge
